### ISSUE TITLE
Backup/restore actions for EasyRSA.

### ISSUE THREAD

**Issue by castrojo** [charmed-kubernetes/bundle#196]
We should consider adding actions for backing up and restoring certificates from EasyRSA so people don't need to manually scp things back and forth.

**Comment by mbruzek** [comment]
I am all for adding this feature to the charm!

It is not clear to me if EasyRSA supports backup/restore, or how to properly do this. EasyRSA creates a "database" and I ran into some problems with when trying to manipulate CA certificates and keys manually. 

More investigation is needed.

**Comment by chuckbutler** [comment]
Adding addendum by duplicated issue 222

We'd need an ability to export the PKI root from easyrsa - and re-import it. I suggest the following workflow.

```
juju run-action easyrsa/0 backup gpg-key=<key_id>
```
This will create a backup and GPG encrypt that payload which will have the PKI bits inside. The action output will present the user with the SCP command to copy down.

For restoring, the user can decrypt the payload on disk and use

```
juju attach easyrsa pki=backup.tar.xz
```

This will trigger a hook run to unpack the PKI infrastructure then re-generate and redistribute certs to all relations.

This will also provide a path forward to "bring your own PKI"

**Comment by hansbogert** [comment]
the charm keeps its own state in the charm's state database for at least the CA certificate as far as I can see. This bit me when I tried to manually move the pki database to another node, but it had no effect
Why doesn't it look in pki/ directory?

**Comment by tvansteenburgh** [comment]
@hansbogert Thanks for documenting these steps. For 7, do you mean you reboot the unit?

**Comment by hansbogert** [comment]
@tvansteenburgh No, simply a `systemctl restart jujud\*easyrsa\*`

**Comment by hansbogert** [comment]
Okay, I tried it another time and I can now say that the following commands actually work:

```
# Login to  node with current easyrsa:
juju ssh 1
  sudo cp -a /var/lib/juju/agents/unit-easyrsa-5/charm/EasyRSA/pki ~/
  # chown to ubuntu so we can read this later on from the juju-client machine with `juju scp`
  sudo chown -R ubuntu:ubuntu pki/
  # Logout
# Get pki folder to juju client
juju scp -- -r   1:pki/ ~/juju/
# Remove old easyrsa unit
juju remove-unit easyrsa/5
# Add new easyrsa unit
juju add-unit easyrsa --to 0
juju scp -- -r   ~/juju/pki   0:pki
juju ssh easyrsa/6
  sudo systemctl stop jujud-unit-easyrsa-6.service 
  sudo rm -rf /var/lib/juju/agents/unit-easyrsa-6/charm/EasyRSA/pki/
  sudo cp -a pki /var/lib/juju/agents/unit-easyrsa-6/charm/
  sudo rm -rf /var/lib/juju/agents/unit-easyrsa-6/charm/.unit-state.db
  cd /var/lib/juju/agents/unit-easyrsa-6/charm/
  # Magic be here. This will skip the recreation of a new pki.
  sudo charms.reactive set_state easyrsa.certificate.authority.available
  sudo systemctl restart jujud-unit-easyrsa-6.service 

```
Done

**Comment by hansbogert** [comment]
@tvansteenburgh I'm actually in the process of spooling my kubernetes/easyrsa node in MAAS. Is there any progress on this in the last 2.5y?

**Comment by Cynerva** [comment]
Nope, we still don't have backup/restore actions for EasyRSA.

Although it's worth noting that, if you lose or remove your EasyRSA unit, then add a new one, the cluster will recover on its own. The CA will be preserved, but other certs will be regenerated.

I'm closing this issue, since we no longer track issues on github. This is being tracked here instead: https://bugs.launchpad.net/charm-easyrsa/+bug/1842152
