### ISSUE TITLE
Add kube-state-metrics to CDK

### ISSUE THREAD

**Issue by mthaddon** [charmed-kubernetes/bundle#717]
We run a number of production clusters of CDK, and on one of them in particular we needed to have visibility on the ready state of pods. After some discussions with folks on the CDK team we deployed https://github.com/kubernetes/kube-state-metrics to this cluster, and are using it to alert us on the state of pods.

This issue is to ask for this to be added to the official CDK offering - we'd prefer not to diverge from upstream in terms of what we're running, and this seems like a useful addition to the bundle.

**Comment by tvansteenburgh** [comment]
Thanks @mthaddon. I've added this to our Ideas list for next cycle's roadmap. If we can get to it before then we will. If there's more urgency than that please let me know.

**Comment by hyperbolic2346** [comment]
@mthaddon Do you have any changes you make to the deployment that you would like to see as options such as memory or cpu limits?

**Comment by DavidSpek** [comment]
I believe this has been added and can be closed.
