### ISSUE TITLE
No place to report a bug for bundles or bundle creation

### ISSUE THREAD

**Issue by nobuto-m** [charmed-kubernetes/bundle#741]
Bug report template says:
> Please file new issues at https://bugs.launchpad.net/charmed-kubernetes.

However, there is no project to report a bug about bundles or bundle creation in https://launchpad.net/charmed-kubernetes

Can you please create a project in Launchpad under charmed-kubernetes and close this issue?

**Comment by tvansteenburgh** [comment]
Project created: https://launchpad.net/charmed-kubernetes-bundles
