### ISSUE TITLE
Namespaced network policies doesn't work with Ingress set to hostNetwork

### ISSUE THREAD

**Issue by niedbalski** [charmed-kubernetes/bundle#765]
[Description]

As indicated on this bug https://github.com/projectcalico/canal/issues/80 and
https://github.com/projectcalico/felix/issues/1361, namespaced network policies doesn't works
directly with containers bind in host networks when using calico, and this is a well known limitation.

The problem is that this commit https://github.com/charmed-kubernetes/charm-kubernetes-worker/blob/4579d7c58c5cdaf3a4ae03ca3cd059082ed615dc/templates/ingress-daemon-set.yaml#L242 Enabled hostnetwork as true by default on the ingress container, which makes impossible to setup network policies on a per-namespace approach.

The only possible workaround is to use CIDR based network policies.

[Reproducer]

1) I've used this juju bundle with k8s 1.17 (http://paste.ubuntu.com/p/GDBMwRrPXy/) + calico (which does hostNetwork: true for ingress by default)

2) I've configured the following 3 replicas deployment:

* http://paste.ubuntu.com/p/6PY7R2NJPG/

3) I've configured the following ingress/service:

* http://paste.ubuntu.com/p/P5x62C7xPN/

4) I've configured a default deny-all policy as follows:

* http://paste.ubuntu.com/p/WNJHG9CSYg/

At this point, the deny all rules works on this particular namespace. That means
that request being forwarded to the other replica pods doesn't work.

5) I configured an additional permit rule using the matchLabels with a given namespace
name, as follows:

* http://paste.ubuntu.com/p/DrfypRK6gP/

This setup doesn't seems to work with labels/namespace filters.

6) If i configure a per CIDR permit rule it does works for the 3 pods.

* http://paste.ubuntu.com/p/pnrhzM6hfK/

10.5.0.0/24 is the network on which my k8s-workers are setup.

ubuntu@niedbalski-bastion:~/cases/00261233/ingress$ curl -H "Host: webserver.10.5.0.59.nip.io"
Hostname: webserver-77f46548c9-st96v
ubuntu@niedbalski-bastion:~/cases/00261233/ingress$ curl -H "Host: webserver.10.5.0.59.nip.io"
Hostname: webserver-77f46548c9-cs6xh
ubuntu@niedbalski-bastion:~/cases/00261233/ingress$ curl -H "Host: webserver.10.5.0.59.nip.io"
Hostname: webserver-77f46548c9-cxcpv

[Possible solutions]

1) Document this limitation and propose to use a node-port configuration rather
than the default ingress.

2) Support port-mappings or another approach that doesn't requires host network
bindings.

[0] https://github.com/charmed-kubernetes/charm-kubernetes-worker/blob/4579d7c58c5cdaf3a4ae03ca3cd059082ed615dc/templates/ingress-daemon-set.yaml#L242

**Comment by tvansteenburgh** [comment]
@niedbalski Thanks, please file this at https://bugs.launchpad.net/charmed-kubernetes - we no longer accept new bugs on this repo.
