### ISSUE TITLE
Cannot go into the pod. error: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)

### ISSUE THREAD

**Issue by Sullivan12138** [charmed-kubernetes/bundle#776]
I created a new kubernetes cluster on my PC using minikube. It's strange that in the beginning I can go into the pod normally, yet after a while I cannot go into the pod. And the error is `error: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)`.
This is an error different from most of those on the Internet, because the description is **Authorization error**, while most of the errors on the Internet are **Forbidden**. I also tried the methods of those solution and it seems not work. 
My PC system is MacOS Catalina 10.15.3. I use minikube version v1.9.2, kubectl client version v1.16.-beta.o, server version v1.18.0, helm version v2.16.3.

**Comment by Cynerva** [comment]
This repo is for a different Kubernetes distribution, Charmed Kubernetes, not minikube. I recommend opening an issue against the minikube repo here: https://github.com/kubernetes/minikube/issues

Sorry we can't really help you here. Best of luck.
